# Generated by Django 4.2.7 on 2023-12-05 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0008_alter_user_options_album_image_album_cover_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="image_album_cover",
            new_name="album_cover_image",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="image_song_cover",
            new_name="song_cover_image",
        ),
    ]
