# Generated by Django 4.2.7 on 2023-12-05 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0009_rename_image_album_cover_album_album_cover_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="album_cover_image",
            new_name="cover_image",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="song_cover_image",
            new_name="cover_image",
        ),
    ]
