# Generated by Django 4.2.7 on 2023-12-05 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0010_rename_album_cover_image_album_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="albums/images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="songs/images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
