# Generated by Django 4.2.7 on 2023-12-06 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0012_alter_album_cover_image_alter_song_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="albums/images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="songs/images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
