# Generated by Django 4.2.7 on 2023-12-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0013_alter_album_cover_image_alter_song_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="albums/images"),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="songs/images"),
        ),
    ]
