# Generated by Django 4.2.7 on 2023-12-15 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0014_alter_album_cover_image_alter_song_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="duration",
        ),
    ]
