# Generated by Django 4.2.7 on 2023-11-13 22:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="release",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
            ),
        ),
    ]
