# Generated by Django 4.2.5 on 2023-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(upload_to="songs"),
        ),
    ]
