# Generated by Django 4.2.7 on 2023-11-10 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="album",
            name="check_album_release_not_in_future",
        ),
        migrations.RemoveConstraint(
            model_name="song",
            name="check_song_release_not_in_future",
        ),
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="check_birth_date_not_in_future",
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release__lte",
                        datetime.datetime(
                            2023,
                            11,
                            10,
                            20,
                            10,
                            59,
                            94579,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_album_release_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release__lte",
                        datetime.datetime(
                            2023,
                            11,
                            10,
                            20,
                            10,
                            59,
                            95022,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_song_release_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(
                            2023,
                            11,
                            10,
                            20,
                            10,
                            59,
                            92977,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_birth_date_not_in_future",
            ),
        ),
    ]
