# Generated by Django 4.2.7 on 2023-11-13 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_alter_album_release_alter_song_release"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="release",
            new_name="release_date",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="release",
            new_name="release_date",
        ),
    ]
