# Generated by Django 4.2.7 on 2023-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_alter_playlist_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
