# Generated by Django 4.2.7 on 2023-11-11 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_remove_album_check_album_release_not_in_future_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="album",
            name="check_album_release_not_in_future",
        ),
        migrations.RemoveConstraint(
            model_name="song",
            name="check_song_release_not_in_future",
        ),
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="check_birth_date_not_in_future",
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release__lte",
                        datetime.datetime(
                            2023,
                            11,
                            11,
                            21,
                            3,
                            37,
                            595902,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_album_release_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release__lte",
                        datetime.datetime(
                            2023,
                            11,
                            11,
                            21,
                            3,
                            37,
                            596344,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_song_release_not_in_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(
                            2023,
                            11,
                            11,
                            21,
                            3,
                            37,
                            594297,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                name="check_birth_date_not_in_future",
            ),
        ),
    ]
