# Generated by Django 4.2.5 on 2023-11-08 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_alter_song_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="release",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created",
            ),
            preserve_default=False,
        ),
    ]
