# Generated by Django 4.2.7 on 2023-11-13 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_alter_song_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="albums", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
