# Generated by Django 4.2.7 on 2023-11-13 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0005_alter_album_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                related_name="albums", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(
                related_name="songs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
