# Generated by Django 4.2.7 on 2023-11-14 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_rename_release_album_release_date_and_more"),
        ("songs", "0006_alter_album_artists_alter_song_artists"),
    ]

    operations = []
