# Generated by Django 4.2.7 on 2023-11-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0008_alter_album_artists_alter_song_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="songs",
                to="songs.album",
            ),
        ),
    ]
